import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Providers } from './providers/providers';
import Nav from './components/Nav';
import { PropsWithChildren } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang='en' className='dark'>
      <body className={`${inter.className}`}>
        <Providers>
          <div className='flex flex-col min-h-screen w-screen'>
            <Nav />
            <main className='h-full w-full flex flex-col justify-center items-center flex-grow'>
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
